### ISSUE TITLE
How does onDotClicked work?

### ISSUE THREAD

**Issue by kentbrew** [jamesroutley/24a2#9]
Rewrote the tutorial game:

https://gist.github.com/kentbrew/505daac747aa17237dfd1bd2105510d9

... tried to work with `onDotClicked` and hit a wall. It returns a number, which does not seem to correspond to a dot on the screen. Also, when you click the same dot twice in a row, nothing happens. Are there any examples for `onDotClicked`?

**Comment by jamesroutley** [comment]
Heya, thank you for taking the time to open an issue!

`onDotClicked` should be a function which takes two numbers, which correspond to the `(x, y)` coordinates of the dot that's been clicked. The x and y values are between 0 and 23, and start from the top left corner. Updating your code to:

```javascript
  onDotClicked = (x, y) => {
    console.log(x, y);
  },
```

looks like it correctly prints out the coordinate of the dot that's been clicked. 

![onDotClicked](https://user-images.githubusercontent.com/5308905/85986841-bc3cba80-b9e4-11ea-87fc-66a057caaa02.gif)

> Also, when you click the same dot twice in a row, nothing happens

I think `console.log` is being called twice - when I tested in Chrome and Firefox both printed a number next to the log line, indicating how many times that line had been logged rather than printing it multiple times. You can see this in the gif above. 

> Are there any examples for onDotClicked?

At the moment, we've only got the [reference documentation](https://24a2.routley.io/reference/interfaces/gameconfig/#optional-ondotclicked), but this is autogenerated from the code, and isn't particularly helpful. I'll add a comment to it saying how it should be called.

**Comment by kentbrew** [comment]
Ah, got it. You'd call getDot with those coordinates to get the color of the dot. Thanks!
